CREATE TABLE IF NOT EXISTS product_variations(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    product_id BIGINT UNSIGNED REFERENCES products(id) ON DELETE CASCADE,
    variation VARCHAR(255) NOT NULL,
    buy_price NUMERIC(8, 2) DEFAULT 0,
    sale_price NUMERIC(8, 2) DEFAULT 0,
    wholesale_price NUMERIC(8, 2) DEFAULT 0,
    recomended_price NUMERIC(8, 2) UNSIGNED NOT NULL DEFAULT 0,
    wholesale_min INT UNSIGNED NOT NULL DEFAULT 1,
    stock INT UNSIGNED NOT NULL DEFAULT 0,
    sold INT UNSIGNED NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);