CREATE TABLE IF NOT EXISTS packages(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    package_category_id BIGINT UNSIGNED NOT NULL REFERENCES package_categories(id) ON DELETE CASCADE,
    name VARCHAR(25) NOT NULL UNIQUE,
    slug VARCHAR(50) NOT NULL UNIQUE,
    amount NUMERIC (10, 2) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);