CREATE TABLE IF NOT EXISTS order_product_variations(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    order_id BIGINT UNSIGNED NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_variation_id BIGINT UNSIGNED NOT NULL REFERENCES product_variations(id) ON DELETE CASCADE,
    selling_price DECIMAL(8, 2) UNSIGNED NOT NULL,
    quantity INT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);