CREATE TABLE IF NOT EXISTS orders(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    user_address_id BIGINT UNSIGNED NOT NULL REFERENCES user_addresses(id) ON DELETE SET NULL,
    ref VARCHAR(8) NOT NULL UNIQUE,
    status ENUM("pending", "delivered") DEFAULT "pending" NOT NULL,
    amount NUMERIC(8, 2) NOT NULL DEFAULT 0,
    discount_amount NUMERIC(8, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);