CREATE TABLE IF NOT EXISTS product_categories(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(45) NOT NULL UNIQUE,
    slug VARCHAR(70) NOT NULL UNIQUE,
    image_path VARCHAR(255) NOT NULL UNIOUE,
    ext VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);
