CREATE TABLE IF NOT EXISTS blogs(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    blog_category_id BIGINT UNSIGNED NOT NULL REFERENCES blog_categories(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL UNIQUE,
    slug VARCHAR(255) NOT NULL UNIQUE,
    description TEXT NOT NULL,
    post LONGTEXT,
    image_path VARCHAR(255),
    link_path VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);