CREATE TABLE IF NOT EXISTS distributor_user_addresses(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  distributor_user_id BIGINT UNSIGNED NOT NULL,
  address VARCHAR(255) NOT NULL,
  phone_number VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(id),
  FOREIGN KEY(distributor_user_id) REFERENCES distributor_users(id) ON DELETE CASCADE ON UPDATE CASCADE
);