CREATE TABLE IF NOT EXISTS distributor_addresses(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  distributor_id BIGINT UNSIGNED NOT NULL,
  address VARCHAR(255) NOT NULL UNIQUE,
  phone_number VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id), 
  FOREIGN KEY (distributor_id) REFERENCES distributors(id) ON DELETE CASCADE ON UPDATE CASCADE
);