CREATE TABLE IF NOT EXISTS distributor_order_packages(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  distributor_order_id BIGINT UNSIGNED NOT NULL REFERENCES distributor_orders(id) ON DELETE CASCADE,
  package_id BIGINT UNSIGNED NOT NULL REFERENCES packages(id) ON DELETE CASCADE,
  quantity INT UNSIGNED NOT NULL,
  amount INT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
  );