CREATE TABLE IF NOT EXISTS domains(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  distributor_id BIGINT UNSIGNED NOT NULL,
  domain VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
);