CREATE TABLE IF NOT EXISTS distributor_product_variations(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  distributor_id BIGINT UNSIGNED NOT NULL REFERENCES distributors(id) ON DELETE CASCADE,
  product_variation_id BIGINT UNSIGNED NOT NULL REFERENCES product_variations (id) ON DELETE CASCADE,
  stock INT UNSIGNED NOT NULL,
  sold INT UNSIGNED NOT NULL DEFAULT 0,
  selling_price DECIMAL(8, 2) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
);