CREATE TABLE IF NOT EXISTS distributor_order_product_variations(
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  distributor_id BIGINT UNSIGNED NOT NULL REFERENCES distributors(id) ON DELETE CASCADE,
  distributor_order_id BIGINT UNSIGNED NOT NULL REFERENCES distributor_orders(id) ON DELETE CASCADE,
  product_variation_id BIGINT UNSIGNED NOT NULL REFERENCES product_variations(id) ON DELETE CASCADE,
  quantity INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
);